name: Build

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Check-out repository
      - uses: actions/checkout@v4

      # Setup Python
      - uses: actions/setup-python@v5
        with:
          # Intentionally using older version of python due to size bloat in later versions that I can't figure out
          # how to eliminate. Seems like most of the increase is in the python.dll which nuitka does not tree-shake.
          # 3.8 binary is ~3 MB
          # 3.11 binary is ~6 MB
          python-version: '3.8'
          cache: 'pip'
      - run: pip install -r requirements.txt

      # Build python script into a single exe
      - name: Build .exe
        run: .\build.bat

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            RegionChanger.py
